{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-zephyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/zephyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/zephyr/zephyr_{{ version }}.tar.gz
  sha256: 89a4ff50c4bdbd7f66ac2e8a07aac55f3596b1c3f17217135bfa4eb4ad86c353

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-glue
    - r-rlang >=1.0.0
  run:
    - r-base
    - r-cli
    - r-glue
    - r-rlang >=1.0.0

test:
  commands:
    - $R -e "library('zephyr')"           # [not win]
    - "\"%R%\" -e \"library('zephyr')\""  # [win]

about:
  home: https://novonordisk-opensource.github.io/zephyr/, https://github.com/novonordisk-opensource/zephyr
  license: Apache-2.0
  summary: Provides a structured framework for consistent user communication and configuration
    management for package developers.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
